- name: Check if PR is from a fork
  id: fork-check
  run: |
    echo "is_fork=$([[ '${{ github.event.pull_request.head.repo.full_name }}' != '${{ github.repository }}' ]] && echo true || echo false)" >> $GITHUB_OUTPUT

- name: Commit and push changes
  if: steps.fork-check.outputs.is_fork == 'false'
  run: |
    git config --global user.name github-actions
    git config --global user.email github-actions@github.com
    git checkout ${{ github.event.pull_request.head.ref }}
    git add CONTRIBUTORS.md
    git commit -m "(CI) format code" || echo "No changes to commit"
    git push origin HEAD:${{ github.event.pull_request.head.ref }}

- name: Skip push (forked PR)
  if: steps.fork-check.outputs.is_fork == 'true'
  run: echo "🔒 Cannot push changes — PR is from a fork. GitHub blocks this."
