name: Sort Users Script

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sort-users:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Run sort_users.py
        run: python sort_users.py
      
      - name: Show changes (if any)
        run: |
          echo "=== Changes made by sort_users.py ==="
          git diff
          echo "=================================="
