name: run-python-sort-script

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  sort-and-check:
    runs-on: ubuntu-latest
    name: Run sort-users.py on all PRs

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Run sort-users.py
        run: |
          echo "Running sort-users.py..."
          python3 sort-users.py
          echo "Script finished running."

      - name: Check if CONTRIBUTORS.md changed
        run: |
          if ! git diff --quiet CONTRIBUTORS.md; then
            echo "❌ CONTRIBUTORS.md is not sorted properly."
            echo "Please run \`python3 sort-users.py\` and commit the result."
            exit 1
          else
            echo "✅ CONTRIBUTORS.md is properly sorted."
          fi
